image: node:18

stages:
  - deploy

variables:
  AWS_REGION: "us-east-1"
  PROJECT_ID: "$CI_PROJECT_NAME"
  DEPLOY_DOMAIN_ROOT: "web.azad.dev"
  DEPLOY_BUCKET: "azad-web-projects"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install -g serverless
  - npm install

deploy:
  stage: deploy
  only:
    - main
  script:
    - |
      export DEPLOY_PREFIX="Users/${USER_ID}/Projects/${PROJECT_ID}"
      cat <<EOF > serverless.yml
      myApp:
        component: "@sls-next/serverless-component@3.7.0"
        inputs:
          name: ${PROJECT_ID}
          bucketName: ${DEPLOY_BUCKET}
          bucketPrefix: ${DEPLOY_PREFIX}
          domain:
            - ${PROJECT_ID}
            - web.kodu.dev
  EOF
    - npx serverless

